export const CREDENTIALS = Symbol('vaultrice/credentials')
export const ENCRYPTION_SETTINGS = Symbol('vaultrice/encryptionSettings')
export const PREVIOUS_ENCRYPTION_SETTINGS = Symbol('vaultrice/previousEncryptionSettings')
export const ERROR_HANDLERS = Symbol('vaultrice/errorHandlers')
export const WEBSOCKET = Symbol('vaultrice/ws')
